"""Deterministic constrained command executor and exact first-wave profile."""

from mem_sandbox.command_executor.commands import (
    CatCommand,
    CdCommand,
    EchoCommand,
    LsCommand,
    MkdirCommand,
    PwdCommand,
    RmCommand,
    TouchCommand,
    create_first_wave_commands,
)
from mem_sandbox.command_executor.errors import (
    CommandCancelled,
    CommandEmpty,
    CommandInternalFailure,
    CommandSyntaxInvalid,
    CommandSyntaxUnsupported,
    CommandTimeout,
    CommandTooLong,
)
from mem_sandbox.command_executor.executor import (
    CommandExecutor,
    VirtualCommandExecutor,
    create_default_executor,
)
from mem_sandbox.command_executor.models import (
    CancellationSignal,
    CommandContext,
    CommandDescriptor,
    CommandEnvironment,
    CommandExecutionContext,
    CommandFailureCode,
    CommandLimits,
    CommandRequest,
    CommandResult,
    CommandWord,
    Connector,
    EnvironmentChange,
    EnvironmentValue,
    ExecuteRequest,
    ExecuteResult,
    ExecutionPlan,
    PlanCommand,
    RedirectionMode,
    StdoutRedirection,
    WordFragment,
)
from mem_sandbox.command_executor.output import (
    BoundedOutputCollector,
    BoundedText,
    bound_text,
)
from mem_sandbox.command_executor.parser import (
    expand_word,
    parse_execution_plan,
    tokenize,
)
from mem_sandbox.command_executor.ports import (
    CommandWorkspaceMutator,
    CommandWorkspaceReader,
)
from mem_sandbox.command_executor.registry import CommandRegistry, VirtualCommand

__all__ = [
    "BoundedOutputCollector",
    "BoundedText",
    "CancellationSignal",
    "CatCommand",
    "CdCommand",
    "CommandCancelled",
    "CommandContext",
    "CommandDescriptor",
    "CommandEmpty",
    "CommandEnvironment",
    "CommandExecutionContext",
    "CommandExecutor",
    "CommandFailureCode",
    "CommandInternalFailure",
    "CommandLimits",
    "CommandRegistry",
    "CommandRequest",
    "CommandResult",
    "CommandSyntaxInvalid",
    "CommandSyntaxUnsupported",
    "CommandTimeout",
    "CommandTooLong",
    "CommandWord",
    "CommandWorkspaceMutator",
    "CommandWorkspaceReader",
    "Connector",
    "EchoCommand",
    "EnvironmentChange",
    "EnvironmentValue",
    "ExecuteRequest",
    "ExecuteResult",
    "ExecutionPlan",
    "LsCommand",
    "MkdirCommand",
    "PlanCommand",
    "PwdCommand",
    "RedirectionMode",
    "RmCommand",
    "StdoutRedirection",
    "TouchCommand",
    "VirtualCommand",
    "VirtualCommandExecutor",
    "WordFragment",
    "bound_text",
    "create_default_executor",
    "create_first_wave_commands",
    "expand_word",
    "parse_execution_plan",
    "tokenize",
]
